### ISSUE TITLE
set Searchbox active when user clicks on the search option

### ISSUE THREAD

**Issue by imabhishekkumar** [imabhishekkumar/PopularMovies_Stage2_Udacity#1]
The search box in the main activity is not by default active when clicked on the search button, the user has to manually click on it again to open the keyboard and start typing.

**Comment by swayangjit** [comment]
Let me try this.

**Comment by swayangjit** [comment]
bottom_nav_color is missing in colors.xml
About.java is missing
Source code is not compiling.
